import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { cn } from "ui";
import {TRPCReactProvider} from "./providers";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html className="light" lang="en">
      <body className={cn(
        'min-h-screen font-sans antialiased',
        inter.className
        )}>
        <TRPCReactProvider headers={headers()}>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
